FROM ubuntu

WORKDIR /var/tmp
ADD crontab /etc/cron.d/ksl-cron
ADD requirements.txt /var/tmp/include/requirements.txt
ENV TZ 'America/Denver'

RUN ["apt-get", "update"]
RUN ["touch", "/etc/timezone"]
RUN echo $TZ > /etc/timezone && \
  apt-get update && apt-get install -y tzdata && \
  rm /etc/localtime && \
  ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
  dpkg-reconfigure -f noninteractive tzdata
RUN ["apt-get", "install", "-y", "wget", "python3", "vim", "cron", "unzip"]
RUN ["dpkg-reconfigure", "-f", "noninteractive", "tzdata"]
RUN ["apt-get", "install", "-y", "chromium-browser"]
RUN ["apt-get", "install", "-y", "python3-pip"]
RUN ["wget", "https://chromedriver.storage.googleapis.com/85.0.4183.83/chromedriver_linux64.zip"]
RUN ["unzip", "chromedriver_linux64.zip", "-d", "/tmp/"]
RUN ["chmod", "777", "/var/tmp/include/requirements.txt"]
RUN ["pip3", "install", "-r", "/var/tmp/include/requirements.txt"]
RUN ["ln", "-s", "/tmp/chromedriver", "/usr/bin"]

RUN chmod 0644 /etc/cron.d/ksl-cron
RUN crontab /etc/cron.d/ksl-cron
CMD ["cron", "-f"]




