FROM ubuntu

WORKDIR /var/tmp
ADD crontab /etc/cron.d/ksl-cron
ADD requirements.txt /var/tmp/include/requirements.txt
ENV TZ 'America/Denver'
RUN apt-get update && \
  touch /etc/timzeone && \
  echo $TZ > /etc/timezone && \
  apt-get update && apt-get install -y tzdata && \
  rm /etc/localtime && \
  ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
  dpkg-reconfigure -f noninteractive tzdata && \
  apt-get install -y wget python3 vim cron unzip gnupg2 && \
  wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
  sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
RUN apt-get update
RUN apt-get install -y google-chrome-stable python3-pip && \
  wget https://chromedriver.storage.googleapis.com/85.0.4183.83/chromedriver_linux64.zip && \
  unzip chromedriver_linux64.zip -d /tmp/ && \
  chmod 777 /var/tmp/include/requirements.txt && \
  pip3 install -r /var/tmp/include/requirements.txt && \
  ln -s /tmp/chromedriver /usr/bin && \
  chmod 0644 /etc/cron.d/ksl-cron && \
  crontab /etc/cron.d/ksl-cron
ENV USING_DOCKER 'TRUE'
CMD ["cron", "-f"]




